# Generated by Django 4.1.5 on 2023-01-05 07:27

from django.db import migrations, models
import django.db.models.deletion
from datetime import datetime

def insert_user(apps, scheme_editor):
  User = apps.get_model('campaignapp', 'User')
  user1 = User(email = "nhat@gmail.com", password = "nhatnhat", first_name = "Quang", last_name = "Nhat", phone_number = "0934676767")
  user1.save()

def insert_campaign(apps, scheme_editor):
  User = apps.get_model('campaignapp', 'User')
  user1 = User.objects.get(email="nhat@gmail.com")

  date_start = datetime.strptime("2017-09-29 00:00:00", "%Y-%m-%d %H:%M:%S")
  date_end = datetime.strptime("2017-10-29 00:00:00", "%Y-%m-%d %H:%M:%S")

  Campaign = apps.get_model('campaignapp', 'Campaign')
  for i in range(9,15):
    campaign = Campaign(name = f"campaign {i}", start_time = date_start, end_time = date_end, budget = 10000, bid_amount = 10, title = "campaign title", description = "desc", banner="banner", final_url="url", used_amount = 0, usage_rate = 0, user_id = user1)
    campaign.save()

def insert_data(apps, scheme_editor):
  pass

class Migration(migrations.Migration):

  initial = True

  dependencies = [
    ('campaignapp', '0001_initial')
  ]

  operations = [
    # migrations.RunPython(insert_user, reverse_code=insert_data),
    migrations.RunPython(insert_campaign, reverse_code=insert_data),
  ]
