# Generated by Django 4.1.5 on 2023-01-05 07:27

from django.db import migrations, models
import django.db.models.deletion
from datetime import datetime

def delete_all_campaign(apps, scheme_editor):

  Campaign = apps.get_model('campaignapp', 'Campaign')
  Campaign.objects.all().delete()

def delete_data(apps, scheme_editor):
  pass

class Migration(migrations.Migration):

  initial = True

  dependencies = [
    ('campaignapp', 'add_data')
  ]

  operations = [
    # migrations.RunPython(insert_user, reverse_code=insert_data),
    migrations.RunPython(delete_all_campaign, reverse_code=delete_data),
  ]
